// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClGRqHYMuduHhg3bGca4DzZLgIroUE0Co',
    appId: '1:9575752169:web:b2dd7ce00142ecbf3eab78',
    messagingSenderId: '9575752169',
    projectId: 'fir-memo-app-26b8c',
    authDomain: 'fir-memo-app-26b8c.firebaseapp.com',
    storageBucket: 'fir-memo-app-26b8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAb3zDL6rXBq2CszWu3WfeqfYnWhq5Zzg',
    appId: '1:9575752169:android:ecf1867b25dfffe73eab78',
    messagingSenderId: '9575752169',
    projectId: 'fir-memo-app-26b8c',
    storageBucket: 'fir-memo-app-26b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMTfdUunbkNdZFXwM1a9LQOZBqk111fY4',
    appId: '1:9575752169:ios:20d81658694364693eab78',
    messagingSenderId: '9575752169',
    projectId: 'fir-memo-app-26b8c',
    storageBucket: 'fir-memo-app-26b8c.appspot.com',
    iosBundleId: 'com.example.memoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMTfdUunbkNdZFXwM1a9LQOZBqk111fY4',
    appId: '1:9575752169:ios:bae2b9f02837b4573eab78',
    messagingSenderId: '9575752169',
    projectId: 'fir-memo-app-26b8c',
    storageBucket: 'fir-memo-app-26b8c.appspot.com',
    iosBundleId: 'com.example.memoApp.RunnerTests',
  );
}
